<?php

namespace Database\Seeders;

use App\Models\OoapMasCourse;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run()
    {
        OoapMasCourse::truncate();

        DB::table('ooap_mas_course')->insert([
            ["code" => "01-01-001-65-001", "name" => "ช่างซ่อมรถจักรยานยนต์ 1", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "1", "coursetype_id" => "1", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-01-002-65-002", "name" => "เครื่องยนต์เล็กเพื่อการเกษตร", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "1", "coursetype_id" => "2", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-02-000-65-003", "name" => "สาขาช่างซ่อมอุปกรณ์ไฟฟ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "2", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-02-000-65-004", "name" => "สาขาช่างเดินสายไฟฟ้าในอาคาร", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "2", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-03-000-65-005", "name" => "สาขาการย้ายและติดตั้งเครื่องปรับอากาศในบ้านและการพาณิชย์ขนาดเล็ก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "3", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-03-000-65-006", "name" => "สาขาการล้างทำความสะอาดเครื่องปรับอากาศในบ้านและการพาณิชย์ขนาดเล็ก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "3", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],


        ]);
    }

    public function run____()
    {
        OoapMasCourse::truncate();

        DB::table('ooap_mas_course')->insert([
            ["code" => "01-01-001-65-001", "name" => "ช่างซ่อมรถจักรยานยนต์ 1", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "1", "coursetype_id" => "1", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-01-002-65-002", "name" => "เครื่องยนต์เล็กเพื่อการเกษตร", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "1", "coursetype_id" => "2", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-02-000-65-003", "name" => "สาขาช่างซ่อมอุปกรณ์ไฟฟ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "2", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-02-000-65-004", "name" => "สาขาช่างเดินสายไฟฟ้าในอาคาร", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "2", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-03-000-65-005", "name" => "สาขาการย้ายและติดตั้งเครื่องปรับอากาศในบ้านและการพาณิชย์ขนาดเล็ก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "3", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-03-000-65-006", "name" => "สาขาการล้างทำความสะอาดเครื่องปรับอากาศในบ้านและการพาณิชย์ขนาดเล็ก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "3", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-03-000-65-007", "name" => "สาขาการบำรุงรักษาเครื่องปรับอากาศในบ้านและการพาณิชย์ขนาดเล็ก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "3", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-04-000-65-008", "name" => "สาขาเทคนิคการติดตั้งจานรับสัญญาณดาวเทียม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "4", "coursetype_id" => NULL, "hour_descp" => "12", "day_descp" => "2", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-04-000-65-009", "name" => "เทคนิคการติดตั้งและบำรุงรักษาระบบเซลล์และแสงอาทิตย์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "4", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-010", "name" => "สาขาการปูกระเบื้องโดยใช้วัสดุกาวซีเมนต์และวัสดุยาแนวที่เป็นมิตรกับสิ่งแวดล้อม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "12", "day_descp" => "2", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-011", "name" => "สาขาการปูพื้น-บุผนัง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-012", "name" => "สาขาการตกแต่งสีลวดลายพิเศษ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-013", "name" => "สาขาการก่ออิฐฉาบปูน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-014", "name" => "สาขาการปูกระเบื้อง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-015", "name" => "สาขาช่างก่อผนังอิฐมวลเบา", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-016", "name" => "สาขาการเดินท่อและติดตั้งสุขภัณฑ์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-017", "name" => "สาขาการทาสีตกแต่ง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-018", "name" => "สาขาการบำรุงรักษาสีอาคาร-สีเครื่องเรือน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-003-65-019", "name" => "สาขาการทำสีตกแต่ง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "3", "hour_descp" => "70", "day_descp" => "12", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-004-65-020", "name" => "สาขาช่างติดตั้งอะลูมิเนียมก่อสร้าง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "4", "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-004-65-021", "name" => "สาขาการทำประตู-หน้าต่างอะลูมิเนียม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "4", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-004-65-022", "name" => "สาขาการทำฝ้าเพดานและผนังโครงอะลูมิเนียม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "4", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-023", "name" => "สาขาการติดตั้งผนังยิปซัม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "6", "day_descp" => "1", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-024", "name" => "สาขาการติดตั้งฝ้าเพดานยิปซัม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "6", "day_descp" => "1", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-025", "name" => "สาขาการประกอบและการติดตั้งโครงอะลูมิเนียม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "6", "day_descp" => "1", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-026", "name" => "สาขาช่างปูพื้นไม้ลามิเนต", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "12", "day_descp" => "2", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-027", "name" => "สาขาการทำกระบะใส่ไม้ประดับทรงสูง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-028", "name" => "สาขาการทำตู้รับจดหมายจากไม้", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-029", "name" => "สาขาการทำผลิตภัณฑ์จากไม้ (ชั้นวางของ)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-030", "name" => "สาขาการทำผลิตภัณฑ์จากไม้ (ที่แขวนผ้า)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "20", "day_descp" => "4", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-031", "name" => "สาขาการประดิษฐ์ชิ้นงานจากไม้", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-032", "name" => "สาขาช่างไม้เครื่องเรือน : การประกอบชิ้นงานไม้", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "01-05-005-65-033", "name" => "สาขาการติดตั้งผนังและฝ้าเพดานยิปซัม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "1", "coursesubgroup_id" => "5", "coursetype_id" => "5", "hour_descp" => "70", "day_descp" => "12", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-034", "name" => "สาขาการปั้นโอ่งซีเมนต์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "180", "day_descp" => "30", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-035", "name" => "การซ่อมเครื่องหนัง (รองเท้าบุรุษ-สตรี)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-036", "name" => "การซ่อมเครื่องหนัง (กระเป๋า)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-037", "name" => "การปรับแบบตัดตามลักษณะรูปร่างของบุคคล", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-038", "name" => "เทคนิคการตกแต่งสีเครื่องเรือน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-039", "name" => "ช่างกระเป๋าเดินทาง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-040", "name" => "การเย็บเบาะจักรยานยนต์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-041", "name" => "การหล่องานหินทราย", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "42", "day_descp" => "7", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-042", "name" => "การจัดสวน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-043", "name" => "การย้อมเส้นใยฝ้ายด้วยสีธรรมชาติ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-044", "name" => "ศิลปะการต่อผ้าและงานควิลท์ การพิมพ์สกรีน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-045", "name" => "การทำพาเลท", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-046", "name" => "การปูพื้นกระเบื้องยาง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-047", "name" => "การปูพื้นไม้บนตง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "02-06-000-65-048", "name" => "การทำเครื่องเรือนไม้ยางพารา", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "2", "coursesubgroup_id" => "6", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-049", "name" => "เทคนิคการทำยางแผ่นคุณภาพ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "21", "day_descp" => "4", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-050", "name" => "เทคนิคการกรีดยาง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "45", "day_descp" => "8", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-051", "name" => "งานกระจกสี (ภาพแขวนและโคมไฟ)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-052", "name" => "งานกระจกสี (การทำช่องหน้าต่าง)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-053", "name" => "การปั้นกระดาษเป็นรูปสัตว์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "28", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-054", "name" => "การปักลวดลายลูกปัดลงบนผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-055", "name" => "การทำและตกแต่งกล่องกระดาษ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "24", "day_descp" => "4", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-056", "name" => "การประดิษฐ์ชิ้นงานจากไม้", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "03-07-000-65-057", "name" => "การทำหินขัด", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "3", "coursesubgroup_id" => "7", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-058", "name" => "การมัดย้อมผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "12", "day_descp" => "2", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-059", "name" => "การปักผ้าเบื้องต้น", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-060", "name" => "การหล่องานเรซิน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-061", "name" => "ศิลปะการปิดทอง (เหรียญพระ,องค์พระ,เครื่องทรง)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-062", "name" => "การทำกรอบพระ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-063", "name" => "การทำและตกแต่งกล่องกระดาษ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "24", "day_descp" => "4", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-064", "name" => "การปั้นกระดาษเป็นรูปสัตว์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "28", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-065", "name" => "เทคนิคการจัดดอกไม้แบบสร้างสรรค์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-066", "name" => "การออกแบบบรรจุภัณฑ์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-067", "name" => "การทำกรอบรูป", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-068", "name" => "การทำหัตถกรรมกระดาษอัด (เปเปร์มาเช่)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-069", "name" => "การทำผลิตภัณฑ์ไฟเบอร์กล๊าส", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-070", "name" => "การทำแม่แบบยางซิลิโคน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-107", "name" => "ผู้ดูแลเด็กและผู้สูงอายุ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "100", "day_descp" => "17", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-108", "name" => "พนักงานนวดแผนไทย", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "100", "day_descp" => "17", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-071", "name" => "ศิลปะการปิดทอง (การสร้างลายรดน้ำ)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-072", "name" => "การทำผลิตภัณฑ์จากด้ายดิบ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-073", "name" => "การเย็บตุ๊กตาผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-074", "name" => "ศิลปะการตกแต่งเล็บมือ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-075", "name" => "การหล่องานปูนเปลือย-หินขัด", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-076", "name" => "การผนึกรูปภาพบนผิววัตถุ (เดคูพาจ)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-077", "name" => "การทำธงประดับ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-078", "name" => "การทำดอกล้วยไม้เคลือบพลาสติก", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-079", "name" => "การทำกล่องเครื่องประดับสำหรับการเดินทาง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-080", "name" => "การชุบดอกไม้ทอง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "30", "day_descp" => "5", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-081", "name" => "การปักลวดลายด้วยลูกปัดลงบนผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-082", "name" => "การประดิษฐ์ดอกไม้เทียนหอม", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-083", "name" => "การผูกผ้าและการพับผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-084", "name" => "การประดิษฐ์ดอกไม้ธนบัตร", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-085", "name" => "การจัดดออกไม้ตกแต่งบ้าน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-086", "name" => "การทำผลิตภัณฑ์จากกะลามะพร้าว", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-087", "name" => "การทำโมบายลูกปัด", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-088", "name" => "การทำเทียนแฟนซี 10 แบบ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-089", "name" => "การแต่งหมอนผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-090", "name" => "การทำเครื่องหอม และน้ำมันหอมระเหยจากพรรณไม้ไทย", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "35", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-091", "name" => "การสร้างสรรค์ผนังอย่างมีดีไซน์", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "36", "day_descp" => "6", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-092", "name" => "ศิลปะการปั้นดอกไม้จากแป้งสบู่", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "42", "day_descp" => "7", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-093", "name" => "หัตกรรมงานหนัง", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "48", "day_descp" => "8", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-094", "name" => "ศิลปะการตกแต่งเสื้อ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-095", "name" => "การทำของใช้ตกแต่งบ้าน", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-096", "name" => "การเพิ่มมูลค่าผลิตภัณฑ์: ออกแบบตุ๊กตาจากเศษผ้า", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-097", "name" => "ศิลปะการตกแต่งเสื้อ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-098", "name" => "การประดิษฐ์ดอกไม้จากกระดาษ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-099", "name" => "เทคนิคการประดิษฐ์และสร้างสรรค์กระเบื้องโมเสค", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "70", "day_descp" => "12", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-08-000-65-100", "name" => "ช่างเย็บจักรอุตสาหกรรม (ทักษะการเย็บชุดชั้นในสตรีเบื้องต้น)", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "8", "coursetype_id" => NULL, "hour_descp" => "180", "day_descp" => "30", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-101", "name" => "10 อันดับเมนูอาหารไทยยอดนิยมในต่างประเทศ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "12", "day_descp" => "2", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-102", "name" => "ผู้ดูแลพนักทำความสะอาด", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "14", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-103", "name" => "พนักงานทำความสะอาด", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-104", "name" => "พนักงานบริการสนามกอล์ฟ", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "18", "day_descp" => "3", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-105", "name" => "เจ้าหน้าที่รักษาความปลอดภัย", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],
            ["code" => "04-09-000-65-106", "name" => "ไทยสปา", "shortname" => "-", "descp" => "-", "dept_id" => "64", "ownertype_id" => "1", "ownerdescp" => "-", "acttype_id" => "2", "coursegroup_id" => "4", "coursesubgroup_id" => "9", "coursetype_id" => NULL, "hour_descp" => "60", "day_descp" => "10", "people_descp" => "16", "trainer_descp" => "1"],

        ]);
    }


}
