<?php

namespace Database\Seeders;

use App\Models\OoapTblEmployee;
use Illuminate\Database\Seeder;
class EmployeeSeeder extends Seeder
{

    public function run()
    {
        OoapTblEmployee::truncate();

        OoapTblEmployee::insert([
            ["emp_citizen_id" => "3660500223393", "new_noti" => NULL, "division_id" => "84", "division_name" => "สำนักงานแรงงานจังหวัดพิจิตร", "province_id" => "23", "role_id" => "2", "from_type" => NULL, "title_th" => "นางสาว", "fname_th" => "เยี่ยมวิมล", "lname_th" => "พาอินทร์", "posit_id" => "4", "posit_name_th" => "นักวิชาการแรงงาน", "positlevel_id" => NULL, "level_no" => NULL, "positlevel_name" => NULL, "direc_id" => NULL, "direc_name" => NULL, "department_id" => "25", "dept_name_th" => "กลุ่มงานยุทธศาสตร์และข้อมูลสารสนเทศ", "personal_type_id" => NULL, "personal_type_name" => NULL, "orgname_id" => NULL, "orgname_type" => NULL, "prefix_id" => NULL, "prefix_name_th" => NULL, "dep_div_id" => NULL, "start_work" => NULL, "birthday" => NULL, "address" => NULL, "phone" => NULL, "email" => NULL, "remark" => NULL, "myooapsys" => NULL, "status" => "1"],
            ["emp_citizen_id" => "tcmad", "new_noti" => "11", "division_id" => "75", "division_name" => "กองยุทธศาสตร์และแผนงาน", "province_id" => NULL, "role_id" => "1", "from_type" => NULL, "title_th" => "Mr.", "fname_th" => "Admin", "lname_th" => "Super", "posit_id" => "2", "posit_name_th" => "ผู้อำนวยการ", "positlevel_id" => "15", "level_no" => "D1", "positlevel_name" => "ประเภทอำนวยการ ระดับต้น", "direc_id" => "1", "direc_name" => "สำนักงานปลัดกระทรวงแรงงาน", "department_id" => NULL, "dept_name_th" => NULL, "personal_type_id" => NULL, "personal_type_name" => NULL, "orgname_id" => NULL, "orgname_type" => NULL, "prefix_id" => NULL, "prefix_name_th" => NULL, "dep_div_id" => NULL, "start_work" => NULL, "birthday" => NULL, "address" => NULL, "phone" => NULL, "email" => NULL, "remark" => NULL, "myooapsys" => "CganyLRbYPMiSLBfjEyrlYa9jkNpacXMyFjRWbNL", "status" => "1"],
            ["emp_citizen_id" => "3840100247455", "new_noti" => NULL, "division_id" => "82", "division_name" => "สำนักงานแรงงานจังหวัดนนทบุรี", "province_id" => "9", "role_id" => "2", "from_type" => NULL, "title_th" => "นาย", "fname_th" => "วิชิตร", "lname_th" => "สุวรรณมาก", "posit_id" => "2", "posit_name_th" => "ผู้อำนวยการ", "positlevel_id" => NULL, "level_no" => NULL, "positlevel_name" => NULL, "direc_id" => NULL, "direc_name" => NULL, "department_id" => NULL, "dept_name_th" => NULL, "personal_type_id" => NULL, "personal_type_name" => NULL, "orgname_id" => NULL, "orgname_type" => NULL, "prefix_id" => NULL, "prefix_name_th" => NULL, "dep_div_id" => NULL, "start_work" => NULL, "birthday" => NULL, "address" => NULL, "phone" => NULL, "email" => NULL, "remark" => NULL, "myooapsys" => "S0PByuAVdPr5UNi0UaZZlMbCr0u1P657RxTqtRel", "status" => "1"],
            ["emp_citizen_id" => "3920200161055", "new_noti" => NULL, "division_id" => "12", "division_name" => "สำนักงานแรงงานจังหวัดตรัง", "province_id" => "68", "role_id" => "3", "from_type" => NULL, "title_th" => "นางสาว", "fname_th" => "วรรณี", "lname_th" => "รองเมือง", "posit_id" => "6", "posit_name_th" => "เจ้าพนักงานการเงินและบัญชี", "positlevel_id" => NULL, "level_no" => NULL, "positlevel_name" => NULL, "direc_id" => NULL, "direc_name" => NULL, "department_id" => "1", "dept_name_th" => "ฝ่ายบริหารทั่วไป", "personal_type_id" => NULL, "personal_type_name" => NULL, "orgname_id" => NULL, "orgname_type" => NULL, "prefix_id" => NULL, "prefix_name_th" => NULL, "dep_div_id" => NULL, "start_work" => NULL, "birthday" => NULL, "address" => NULL, "phone" => NULL, "email" => NULL, "remark" => NULL, "myooapsys" => "m7AxGeh9o4geD75A8C1xwf5wdr9WRQQSxxhC3033", "status" => "1"],
            ["emp_citizen_id" => "3969800001863", "new_noti" => NULL, "division_id" => "87", "division_name" => "สำนักงานแรงงานจังหวัดปราจีนบุรี", "province_id" => "62", "role_id" => "3", "from_type" => NULL, "title_th" => "นาง", "fname_th" => "ประไพพรรณ", "lname_th" => "ลุ่มจันทร์", "posit_id" => "2", "posit_name_th" => "ผู้อำนวยการ", "positlevel_id" => NULL, "level_no" => NULL, "positlevel_name" => NULL, "direc_id" => NULL, "direc_name" => NULL, "department_id" => NULL, "dept_name_th" => NULL, "personal_type_id" => NULL, "personal_type_name" => NULL, "orgname_id" => NULL, "orgname_type" => NULL, "prefix_id" => NULL, "prefix_name_th" => NULL, "dep_div_id" => NULL, "start_work" => NULL, "birthday" => NULL, "address" => NULL, "phone" => NULL, "email" => NULL, "remark" => NULL, "myooapsys" => NULL, "status" => "1"],
        ]);
    }
}
