<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\OoapMasDivision;

//ooap_mas_divisions_seed
class OoapMasDivisionSeeder extends Seeder
{
    public function run()
    {
        OoapMasDivision::truncate();

        OoapMasDivision::insert([

            ["division_name" => "สำนักงานแรงงานในต่างประเทศ", "province_id" => NULL],
            ["division_name" => "สำนักงานสภาที่ปรึกษาเพื่อพัฒนาแรงงานแห่งชาติ", "province_id" => NULL],
            ["division_name" => "สำนักงานเลขานุการศูนย์บัญชาการป้องกันการค้ามนุษย์ด้านแรงงาน", "province_id" => NULL],
            ["division_name" => "สำนักงานคณะกรรมการค่าจ้าง", "province_id" => NULL],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครปฐม", "province_id" => "2"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสุโขทัย", "province_id" => "32"],
            ["division_name" => "สำนักงานแรงงานจังหวัดยะลา", "province_id" => "69"],
            ["division_name" => "สำนักงานแรงงานจังหวัดกาฬสินธุ์", "province_id" => "35"],
            ["division_name" => "สำนักงานแรงงานจังหวัดบุรีรัมย์", "province_id" => "45"],
            ["division_name" => "สำนักงานแรงงานจังหวัดภูเก็ต", "province_id" => "70"],
            ["division_name" => "สำนักงานแรงงานจังหวัดยโสธร", "province_id" => "44"],
            ["division_name" => "สำนักงานแรงงานจังหวัดตรัง", "province_id" => "68"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพังงา", "province_id" => "74"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครราชสีมา", "province_id" => "37"],
            ["division_name" => "สำนักงานแรงงานจังหวัดตราด", "province_id" => "57"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอุดรธานี", "province_id" => "63"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครสวรรค์", "province_id" => "25"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพะเยา", "province_id" => "22"],
            ["division_name" => "สำนักงานแรงงานจังหวัดแม่ฮ่องสอน", "province_id" => "30"],
            ["division_name" => "สำนักงานแรงงานจังหวัดราชบุรี", "province_id" => "11"],
            ["division_name" => "สำนักงานแรงงานจังหวัดศรีสะเกษ", "province_id" => "47"],
            ["division_name" => "สำนักงานแรงงานจังหวัดลำพูน", "province_id" => "34"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพิษณุโลก", "province_id" => "24"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสิงห์บุรี", "province_id" => "17"],
            ["division_name" => "สำนักงานแรงงานจังหวัดหนองบัวลำภู", "province_id" => "51"],
            ["division_name" => "สำนักงานแรงงานจังหวัดประจวบคีรีขันธ์", "province_id" => "6"],
            ["division_name" => "สำนักงานแรงงานจังหวัดระยอง", "province_id" => "65"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสมุทรปราการ", "province_id" => "20"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอุตรดิตถ์", "province_id" => "33"],
            ["division_name" => "สำนักงานแรงงานจังหวัดมหาสารคาม", "province_id" => "42"],
            ["division_name" => "สำนักงานแรงงานจังหวัดชุมพร", "province_id" => "60"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสระแก้ว", "province_id" => "59"],
            ["division_name" => "สำนักงานแรงงานจังหวัดชัยภูมิ", "province_id" => "40"],
            ["division_name" => "สำนักตรวจและประเมินผล", "province_id" => NULL],
            ["division_name" => "สำนักงานแรงงานจังหวัดกาญจนบุรี", "province_id" => "5"],
            ["division_name" => "สำนักงานแรงงานจังหวัดหนองคาย", "province_id" => "56"],
            ["division_name" => "สำนักงานแรงงานจังหวัดปทุมธานี", "province_id" => "4"],
            ["division_name" => "สำนักงานแรงงานจังหวัดแพร่", "province_id" => "31"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอุบลราชธานี", "province_id" => "55"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพัทลุง", "province_id" => "71"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสตูล", "province_id" => "72"],
            ["division_name" => "สำนักงานแรงงานจังหวัดลำปาง", "province_id" => "28"],
            ["division_name" => "สำนักงานแรงงานจังหวัดกำแพงเพชร", "province_id" => "27"],
            ["division_name" => "สำนักงานแรงงานจังหวัดปัตตานี", "province_id" => "66"],
            ["division_name" => "สำนักงานแรงงานจังหวัดลพบุรี", "province_id" => "10"],
            ["division_name" => "สำนักงานแรงงานจังหวัดชลบุรี", "province_id" => "58"],
            ["division_name" => "สำนักงานแรงงานจังหวัดชัยนาท", "province_id" => "3"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสมุทรสงคราม", "province_id" => "14"],
            ["division_name" => "สำนักงานแรงงานจังหวัดเพชรบุรี", "province_id" => "7"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสกลนคร", "province_id" => "46"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสงขลา", "province_id" => "73"],
            ["division_name" => "สำนักงานแรงงานจังหวัดน่าน", "province_id" => "36"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนราธิวาส", "province_id" => "64"],
            ["division_name" => "สำนักงานแรงงานจังหวัดร้อยเอ็ด", "province_id" => "48"],
            ["division_name" => "สำนักงานแรงงานจังหวัดกระบี่", "province_id" => "77"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสุราษฎร์ธานี", "province_id" => "75"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอุทัยธานี", "province_id" => "39"],
            ["division_name" => "สำนักงานแรงงานจังหวัดเชียงราย", "province_id" => "21"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครศรีธรรมราช", "province_id" => "67"],
            ["division_name" => "สำนักงานแรงงานจังหวัดระนอง", "province_id" => "76"],
            ["division_name" => "สำนักงานแรงงานจังหวัดเพชรบูรณ์", "province_id" => "26"],
            ["division_name" => "สำนักงานแรงงานจังหวัดมุกดาหาร", "province_id" => "50"],
            ["division_name" => "สำนักงานแรงงานจังหวัดตาก", "province_id" => "19"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสุรินทร์", "province_id" => "53"],
            ["division_name" => "สำนักงานแรงงานจังหวัดจันทบุรี", "province_id" => "61"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสระบุรี", "province_id" => "13"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครพนม", "province_id" => "43"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอำนาจเจริญ", "province_id" => "52"],
            ["division_name" => "สำนักงานรัฐมนตรี", "province_id" => NULL],
            ["division_name" => "ศูนย์บริการประชาชนกระทรวงแรงงาน", "province_id" => NULL],
            ["division_name" => "ศูนย์ปฏิบัติการต่อต้านการทุจริต", "province_id" => NULL],
            ["division_name" => "ศูนย์วิจัยและนวัตกรรมแรงงาน", "province_id" => NULL],
            ["division_name" => "กองกลาง", "province_id" => NULL],
            ["division_name" => "กองบริหารการคลัง", "province_id" => NULL],
            ["division_name" => "กองยุทธศาสตร์และแผนงาน", "province_id" => NULL],
            ["division_name" => "กองบริหารทรัพยากรบุคคล", "province_id" => NULL],
            ["division_name" => "กองกฎหมาย", "province_id" => NULL],
            ["division_name" => "สำนักงานแรงงานจังหวัดขอนแก่น", "province_id" => "38"],
            ["division_name" => "สำนักประสานความร่วมมือระหว่างประเทศ", "province_id" => NULL],
            ["division_name" => "สำนักงานแรงงานจังหวัดฉะเชิงเทรา", "province_id" => "54"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสุพรรณบุรี", "province_id" => "15"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนนทบุรี", "province_id" => "9"],
            ["division_name" => "สำนักงานแรงงานจังหวัดสมุทรสาคร", "province_id" => "12"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพิจิตร", "province_id" => "23"],
            ["division_name" => "สำนักงานแรงงานจังหวัดนครนายก", "province_id" => "8"],
            ["division_name" => "สำนักงานแรงงานจังหวัดพระนครศรีอยุธยา", "province_id" => "16"],
            ["division_name" => "สำนักงานแรงงานจังหวัดปราจีนบุรี", "province_id" => "62"],
            ["division_name" => "สำนักงานแรงงานจังหวัดบึงกาฬ", "province_id" => "41"],
            ["division_name" => "สำนักงานแรงงานจังหวัดอ่างทอง", "province_id" => "18"],
            ["division_name" => "สำนักงานแรงงานจังหวัดเชียงใหม่", "province_id" => "29"],
            ["division_name" => "สำนักงานแรงงานจังหวัดเลย", "province_id" => "49"],
            ["division_name" => "ศูนย์เทคโนโลยีสารสนเทศและการสื่อสาร", "province_id" => NULL],
            ["division_name" => "กองเผยแพร่และประชาสัมพันธ์", "province_id" => NULL],
            ["division_name" => "กองเศรษฐกิจการแรงงาน", "province_id" => NULL],
            ["division_name" => "ราชการบริหารส่วนกลาง", "province_id" => NULL],
            ["division_name" => "กลุ่มตรวจสอบภายใน", "province_id" => NULL],
            ["division_name" => "กลุ่มพัฒนาระบบบริหาร", "province_id" => NULL],
            ["division_name" => "กลุ่มขับเคลื่อนการปฏิรูปประเทศ ยุทธศาสตร์ชาติ และการสร้างความสามัคคีปรองดอง", "province_id" => NULL],
            ["division_name" => "ศูนย์บริหารแรงงานเขตพัฒนาพิเศษภาคตะวันออก", "province_id" => NULL],
            ["division_name" => "สานักงานนโยบายแรงงานนอกระบบ", "province_id" => NULL],
        ]);
    }
}
