<?php

namespace Database\Seeders;

use App\Models\OoapTblRequest;
use Illuminate\Database\Seeder;

//ooap_tbl_requests_seed
class RequestsSeeder extends Seeder
{

    public function run()
    {
        OoapTblRequest::truncate();

        OoapTblRequest::insert([
            ["req_div" => "58", "req_province" => "5", "in_active" => NULL, "status" => "3", "req_acttype" => "2", "req_amount" => "3440", "req_number" => "RF-6511-00099", "req_year" => "2565", "req_dept" => NULL, "req_course" => NULL, "req_coursegroup" => "81", "req_coursesubgroup" => NULL, "req_coursetype" => NULL, "req_shortname" => "addsds", "req_desc" => "a", "req_remark" => NULL, "req_troubletype" => NULL, "req_peopleno" => NULL, "req_moo" => NULL, "req_district" => "814", "req_subdistrict" => "13807", "req_commu" => NULL, "req_leadname" => "a", "req_position" => "a", "req_leadinfo" => "a", "req_buildtypeid" => NULL, "req_buildname" => "a", "req_latitude" => NULL, "req_longtitude" => NULL, "req_measure" => NULL, "req_metric" => NULL, "req_width" => NULL, "req_length" => NULL, "req_height" => NULL, "req_unit" => NULL, "req_startmonth" => "2022-11-01", "req_endmonth" => "2022-11-01", "req_numofday" => "2", "req_numofpeople" => "1", "req_numlecturer" => "1", "req_rate" => "600", "req_foodrate" => "120", "req_materialrate" => "1000", "req_otheramt" => "1000", "req_amtfood" => "240", "req_amtlecturer" => "1200", "req_materialamt" => "1000", "req_hrperday" => "6", "req_sendappdate" => NULL, "req_approvedate" => NULL, "req_approveby" => NULL, "req_approvenote" => NULL],
            ["req_div" => "58", "req_province" => "62", "in_active" => NULL, "status" => "3", "req_acttype" => "2", "req_amount" => "3440", "req_number" => "RF-6511-0001", "req_year" => "2565", "req_dept" => NULL, "req_course" => NULL, "req_coursegroup" => "81", "req_coursesubgroup" => NULL, "req_coursetype" => NULL, "req_shortname" => "343434", "req_desc" => "a", "req_remark" => NULL, "req_troubletype" => NULL, "req_peopleno" => NULL, "req_moo" => NULL, "req_district" => "814", "req_subdistrict" => "13807", "req_commu" => NULL, "req_leadname" => "a", "req_position" => "a", "req_leadinfo" => "a", "req_buildtypeid" => NULL, "req_buildname" => "a", "req_latitude" => NULL, "req_longtitude" => NULL, "req_measure" => NULL, "req_metric" => NULL, "req_width" => NULL, "req_length" => NULL, "req_height" => NULL, "req_unit" => NULL, "req_startmonth" => "2022-11-01", "req_endmonth" => "2022-11-01", "req_numofday" => "2", "req_numofpeople" => "1", "req_numlecturer" => "1", "req_rate" => "600", "req_foodrate" => "120", "req_materialrate" => "1000", "req_otheramt" => "1000", "req_amtfood" => "240", "req_amtlecturer" => "1200", "req_materialamt" => "1000", "req_hrperday" => "6", "req_sendappdate" => NULL, "req_approvedate" => NULL, "req_approveby" => NULL, "req_approvenote" => NULL],
            ["req_div" => "58", "req_province" => "62", "in_active" => NULL, "status" => "3", "req_acttype" => "2", "req_amount" => "3440", "req_number" => "RF-6411-0002", "req_year" => "2564", "req_dept" => NULL, "req_course" => NULL, "req_coursegroup" => "81", "req_coursesubgroup" => NULL, "req_coursetype" => NULL, "req_shortname" => "adds", "req_desc" => "a", "req_remark" => NULL, "req_troubletype" => NULL, "req_peopleno" => NULL, "req_moo" => NULL, "req_district" => "814", "req_subdistrict" => "13807", "req_commu" => NULL, "req_leadname" => "a", "req_position" => "a", "req_leadinfo" => "a", "req_buildtypeid" => NULL, "req_buildname" => "a", "req_latitude" => NULL, "req_longtitude" => NULL, "req_measure" => NULL, "req_metric" => NULL, "req_width" => NULL, "req_length" => NULL, "req_height" => NULL, "req_unit" => NULL, "req_startmonth" => "2022-11-01", "req_endmonth" => "2022-11-01", "req_numofday" => "2", "req_numofpeople" => "1", "req_numlecturer" => "1", "req_rate" => "600", "req_foodrate" => "120", "req_materialrate" => "1000", "req_otheramt" => "1000", "req_amtfood" => "240", "req_amtlecturer" => "1200", "req_materialamt" => "1000", "req_hrperday" => "6", "req_sendappdate" => NULL, "req_approvedate" => NULL, "req_approveby" => NULL, "req_approvenote" => NULL],
            ["req_div" => "58", "req_province" => "62", "in_active" => NULL, "status" => "3", "req_acttype" => "1", "req_amount" => "5000", "req_number" => "RF-6411-0003", "req_year" => "2564", "req_dept" => NULL, "req_course" => NULL, "req_coursegroup" => "81", "req_coursesubgroup" => NULL, "req_coursetype" => NULL, "req_shortname" => "adsadasf", "req_desc" => "a", "req_remark" => NULL, "req_troubletype" => NULL, "req_peopleno" => NULL, "req_moo" => NULL, "req_district" => "814", "req_subdistrict" => "13807", "req_commu" => NULL, "req_leadname" => "a", "req_position" => "a", "req_leadinfo" => "a", "req_buildtypeid" => NULL, "req_buildname" => "a", "req_latitude" => NULL, "req_longtitude" => NULL, "req_measure" => NULL, "req_metric" => NULL, "req_width" => NULL, "req_length" => NULL, "req_height" => NULL, "req_unit" => NULL, "req_startmonth" => "2022-11-01", "req_endmonth" => "2022-11-01", "req_numofday" => "2", "req_numofpeople" => "1", "req_numlecturer" => "1", "req_rate" => "600", "req_foodrate" => "120", "req_materialrate" => "1000", "req_otheramt" => "1000", "req_amtfood" => "240", "req_amtlecturer" => "1200", "req_materialamt" => "1000", "req_hrperday" => "6", "req_sendappdate" => NULL, "req_approvedate" => NULL, "req_approveby" => NULL, "req_approvenote" => NULL],

        ]);
    }
}
