<?php

namespace Database\Seeders;

use App\Models\OoapTblActivities;
use Illuminate\Database\Seeder;

class TblActivitiesSeeder extends Seeder
{
    public function run()
    {

        //ooap_tbl_activities_seed
        OoapTblActivities::truncate();

        OoapTblActivities::insert([

            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => "3", "people_checkin" => "3", "people_not_checkin" => 0, "act_number" => "AT-6511-0002", "act_year" => "2565", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "1", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "1", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],
            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => NULL, "people_checkin" => 0, "people_not_checkin" => 0, "act_number" => "AT-6511-00029", "act_year" => "2565", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "1", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "2", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],
            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => "1", "people_checkin" => "1", "people_not_checkin" => 0, "act_number" => "AT-6511-000299", "act_year" => "2566", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "1", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "1", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],
            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => NULL, "people_checkin" => 0, "people_not_checkin" => 0, "act_number" => "AT-6511-000299หกหก", "act_year" => "2565", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "1", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "4", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],
            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => NULL, "people_checkin" => 0, "people_not_checkin" => 0, "act_number" => "กกฟห9หกหก", "act_year" => "2564", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "1", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "4", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],
            ["templateno_count" => "5", "templateno" => "221108-020542", "act_shortname" => "กหดกหกห", "people_all" => NULL, "people_checkin" => 0, "people_not_checkin" => 0, "act_number" => "กกกหกหกห", "act_year" => "2565", "act_periodno" => NULL, "act_dept" => NULL, "act_div" => NULL, "act_province" => "1", "act_district" => NULL, "act_subdistrict" => "5376", "act_moo" => NULL, "act_commu" => NULL, "act_leadname" => NULL, "act_position" => NULL, "act_leadinfo" => NULL, "act_startmonth" => NULL, "act_endmonth" => NULL, "act_numofday" => NULL, "act_numofpeople" => NULL, "act_rate" => NULL, "act_amount" => NULL, "act_acttype" => "2", "act_desc" => NULL, "act_remark" => NULL, "act_troubletype" => NULL, "act_peopleno" => NULL, "act_buildtypeid" => NULL, "act_buildname" => NULL, "act_latitude" => NULL, "act_longtitude" => NULL, "act_measure" => NULL, "act_metric" => NULL, "act_width" => NULL, "act_length" => NULL, "act_height" => NULL, "act_unit" => NULL, "act_course" => NULL, "act_coursegroup" => "4", "act_coursesubgroup" => NULL, "act_numlecturer" => NULL, "act_foodrate" => NULL, "act_amtfood" => NULL, "act_amtlecturer" => NULL, "act_materialrate" => NULL, "act_materialamt" => NULL, "act_otheramt" => NULL, "act_hrperday" => NULL, "act_sendappdate" => NULL, "act_approvedate" => NULL, "act_approveby" => NULL, "act_approvenote" => NULL, "templateno" => "221108-020542", "pop_income" => 0],



        ]);
    }
}
