<?php

namespace Database\Seeders;

use App\Models\PER_LEVEL;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PerLevelSeeder extends Seeder
{

    public function run()
    {

        PER_LEVEL::truncate();

        if( DB::connection()->getDatabaseName() == 'bombtest2') {

            return ;
        }

        DB::table('per_level')->insert([

            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ชั้นต้น", "per_type" => "1.00", "level_shortname" => "ชั้นต้น", "level_seq_no" => "12.00", "position_type" => NULL, "position_level" => NULL, "level_othername" => NULL, "level_engname" => NULL, "level_no" => "1", "update_date" => "2018-12-21 09:17:41"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ชั้นกลาง", "per_type" => "1.00", "level_shortname" => "ชั้นกลาง", "level_seq_no" => "13.00", "position_type" => NULL, "position_level" => NULL, "level_othername" => NULL, "level_engname" => NULL, "level_no" => "2", "update_date" => "2018-12-19 14:25:17"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ชั้นสูง", "per_type" => "1.00", "level_shortname" => "ชั้นสูง", "level_seq_no" => "14.00", "position_type" => NULL, "position_level" => NULL, "level_othername" => NULL, "level_engname" => NULL, "level_no" => "3", "update_date" => "2018-12-19 14:26:51"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "4", "per_type" => "1.00", "level_shortname" => "ผู้จัดการ", "level_seq_no" => "15.00", "position_type" => "4", "position_level" => "4", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "4", "update_date" => "2017-06-21 13:13:23"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "5", "per_type" => "1.00", "level_shortname" => "ผู้จัดการอาวุโส", "level_seq_no" => "16.00", "position_type" => "5", "position_level" => "5", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "5", "update_date" => "2018-08-30 15:23:08"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "6", "per_type" => "1.00", "level_shortname" => "ผู้บริหารสายงาน", "level_seq_no" => "17.00", "position_type" => "6", "position_level" => "6", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "6", "update_date" => "2017-06-21 13:14:04"],
            ["level_active" => "0.00", "update_user" => "3092.00", "level_name" => "กลุ่มงานเทคนิคพิเศษ", "per_type" => "3.00", "level_shortname" => "เทคนิคพิเศษ", "level_seq_no" => "67.00", "position_type" => NULL, "position_level" => "กลุ่มงานเทคนิคพิเศษ", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E7", "update_date" => "2010-10-18 13:30:37"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 10", "per_type" => "1.00", "level_shortname" => "10", "level_seq_no" => "10.00", "position_type" => NULL, "position_level" => " 10", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "10", "update_date" => "2004-01-06 16:38:35"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 11", "per_type" => "1.00", "level_shortname" => "11", "level_seq_no" => "11.00", "position_type" => NULL, "position_level" => " 11", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "11", "update_date" => "2004-01-06 16:38:35"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ชั้นต้น", "per_type" => "1.00", "level_shortname" => "ชั้นต้น", "level_seq_no" => "0.00", "position_type" => "ชั้นต้น", "position_level" => "ชั้นต้น", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "01", "update_date" => "2019-11-26 13:56:47"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ชั้นกลาง", "per_type" => "1.00", "level_shortname" => "ชั้นกลาง", "level_seq_no" => "0.00", "position_type" => "ชั้นกลาง", "position_level" => "ชั้นกลาง", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "02", "update_date" => "2019-11-26 13:57:02"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ชั้นสูง", "per_type" => "1.00", "level_shortname" => "ชั้นสูง", "level_seq_no" => "0.00", "position_type" => "ชั้นสูง", "position_level" => "ชั้นสูง", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "03", "update_date" => "2019-11-26 13:57:13"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 4", "per_type" => "1.00", "level_shortname" => "4", "level_seq_no" => "4.00", "position_type" => NULL, "position_level" => " 4", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "04", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 5", "per_type" => "1.00", "level_shortname" => "5", "level_seq_no" => "5.00", "position_type" => NULL, "position_level" => " 5", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "05", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 6", "per_type" => "1.00", "level_shortname" => "6", "level_seq_no" => "6.00", "position_type" => NULL, "position_level" => " 6", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "06", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 7", "per_type" => "1.00", "level_shortname" => "7", "level_seq_no" => "7.00", "position_type" => NULL, "position_level" => " 7", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "07", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 8", "per_type" => "1.00", "level_shortname" => "8", "level_seq_no" => "8.00", "position_type" => NULL, "position_level" => " 8", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "08", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ 9", "per_type" => "1.00", "level_shortname" => "9", "level_seq_no" => "9.00", "position_type" => NULL, "position_level" => " 9", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "09", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภททั่วไป ระดับปฏิบัติงาน", "per_type" => "1.00", "level_shortname" => "ปง.", "level_seq_no" => "21.00", "position_type" => "ทั่วไป", "position_level" => "ปฏิบัติงาน", "level_othername" => NULL, "level_engname" => "Operational Level", "level_no" => "O1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภททั่วไป ระดับชำนาญงาน", "per_type" => "1.00", "level_shortname" => "ชง.", "level_seq_no" => "22.00", "position_type" => "ทั่วไป", "position_level" => "ชำนาญงาน", "level_othername" => NULL, "level_engname" => "Experienced Level", "level_no" => "O2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภททั่วไป ระดับอาวุโส", "per_type" => "1.00", "level_shortname" => "อว.", "level_seq_no" => "23.00", "position_type" => "ทั่วไป", "position_level" => "อาวุโส", "level_othername" => NULL, "level_engname" => "Senior Level", "level_no" => "O3", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภททั่วไป ระดับทักษะพิเศษ", "per_type" => "1.00", "level_shortname" => "ทพ.", "level_seq_no" => "24.00", "position_type" => "ทั่วไป", "position_level" => "ทักษะพิเศษ", "level_othername" => NULL, "level_engname" => "Highly Skilled Level", "level_no" => "O4", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทวิชาการ ระดับปฏิบัติการ", "per_type" => "1.00", "level_shortname" => "ปก.", "level_seq_no" => "31.00", "position_type" => "วิชาการ", "position_level" => "ปฏิบัติการ", "level_othername" => NULL, "level_engname" => "Practitioner Level", "level_no" => "K1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทวิชาการ ระดับชำนาญการ", "per_type" => "1.00", "level_shortname" => "ชก.", "level_seq_no" => "32.00", "position_type" => "วิชาการ", "position_level" => "ชำนาญการ", "level_othername" => NULL, "level_engname" => "Professional Level", "level_no" => "K2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทวิชาการ ระดับชำนาญการพิเศษ", "per_type" => "1.00", "level_shortname" => "ชพ.", "level_seq_no" => "33.00", "position_type" => "วิชาการ", "position_level" => "ชำนาญการพิเศษ", "level_othername" => NULL, "level_engname" => "Senior Professional Level", "level_no" => "K3", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทวิชาการ ระดับเชี่ยวชาญ", "per_type" => "1.00", "level_shortname" => "ชช.", "level_seq_no" => "34.00", "position_type" => "วิชาการ", "position_level" => "เชี่ยวชาญ", "level_othername" => NULL, "level_engname" => "Expert Level", "level_no" => "K4", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทวิชาการ ระดับทรงคุณวุฒิ", "per_type" => "1.00", "level_shortname" => "ทว.", "level_seq_no" => "35.00", "position_type" => "วิชาการ", "position_level" => "ทรงคุณวุฒิ", "level_othername" => NULL, "level_engname" => "Advisory Level", "level_no" => "K5", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทอำนวยการ ระดับต้น", "per_type" => "1.00", "level_shortname" => "อต.", "level_seq_no" => "41.00", "position_type" => "อำนวยการ", "position_level" => "ต้น", "level_othername" => NULL, "level_engname" => "Primary Level", "level_no" => "D1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทอำนวยการ ระดับสูง", "per_type" => "1.00", "level_shortname" => "อส.", "level_seq_no" => "42.00", "position_type" => "อำนวยการ", "position_level" => "สูง", "level_othername" => NULL, "level_engname" => "Higher Level", "level_no" => "D2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทบริหาร ระดับต้น", "per_type" => "1.00", "level_shortname" => "บต.", "level_seq_no" => "51.00", "position_type" => "บริหาร", "position_level" => "ต้น", "level_othername" => NULL, "level_engname" => "Primary Level", "level_no" => "M1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ประเภทบริหาร ระดับสูง", "per_type" => "1.00", "level_shortname" => "บส.", "level_seq_no" => "52.00", "position_type" => "บริหาร", "position_level" => "สูง", "level_othername" => NULL, "level_engname" => "Higher Level", "level_no" => "M2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานบริการ", "per_type" => "3.00", "level_shortname" => "บริการ", "level_seq_no" => "61.00", "position_type" => NULL, "position_level" => "กลุ่มงานบริการ", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานเทคนิคทั่วไป", "per_type" => "3.00", "level_shortname" => "เทคนิคทั่วไป", "level_seq_no" => "62.00", "position_type" => NULL, "position_level" => "กลุ่มงานเทคนิค", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานบริหารทั่วไป", "per_type" => "3.00", "level_shortname" => "บริหารทั่วไป", "level_seq_no" => "63.00", "position_type" => NULL, "position_level" => "กลุ่มงานบริหารทั่วไป", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E3", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานวิชาชีพเฉพาะ", "per_type" => "3.00", "level_shortname" => "วิชาชีพเฉพาะ", "level_seq_no" => "64.00", "position_type" => NULL, "position_level" => "กลุ่มงานวิชาชีพเฉพาะ", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E4", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานเชี่ยวชาญเฉพาะ", "per_type" => "3.00", "level_shortname" => "เชี่ยวชาญเฉพาะ", "level_seq_no" => "65.00", "position_type" => NULL, "position_level" => "กลุ่มงานเชี่ยวชาญเฉพาะ", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "E5", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับทั่วไป)", "per_type" => "3.00", "level_shortname" => "ระดับทั่วไป", "level_seq_no" => "71.00", "position_type" => NULL, "position_level" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับทั่วไป)", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "S1", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับประเทศ)", "per_type" => "3.00", "level_shortname" => "ระดับประเทศ", "level_seq_no" => "72.00", "position_type" => NULL, "position_level" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับประเทศ)", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "S2", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับสากล)", "per_type" => "3.00", "level_shortname" => "ระดับสากล", "level_seq_no" => "73.00", "position_type" => NULL, "position_level" => "กลุ่มงานเชี่ยวชาญพิเศษ (ระดับสากล)", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "S3", "update_date" => "2007-05-11 13:22:07"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ บ1", "per_type" => "2.00", "level_shortname" => "บ1", "level_seq_no" => "11.00", "position_type" => "กลุ่มงานบริการพื้นฐาน", "position_level" => "ระดับ บ1", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "บ1", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ บ2", "per_type" => "2.00", "level_shortname" => "บ2", "level_seq_no" => "12.00", "position_type" => "กลุ่มงานบริการพื้นฐาน", "position_level" => "ระดับ บ2", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "บ2", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ บ2/หัวหน้า", "per_type" => "2.00", "level_shortname" => "บ2/หน.", "level_seq_no" => "13.00", "position_type" => "กลุ่มงานบริการพื้นฐาน", "position_level" => "ระดับ บ2/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "บ3", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส1", "per_type" => "2.00", "level_shortname" => "ส1", "level_seq_no" => "21.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส1", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส1", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส2", "per_type" => "2.00", "level_shortname" => "ส2", "level_seq_no" => "22.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส2", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส2", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส2/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ส2/หน.", "level_seq_no" => "23.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส2/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส3", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส3", "per_type" => "2.00", "level_shortname" => "ส3", "level_seq_no" => "24.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส3", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส4", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส3/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ส3/หน.", "level_seq_no" => "25.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส3/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส5", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส4", "per_type" => "2.00", "level_shortname" => "ส4", "level_seq_no" => "26.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส4", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส6", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ส4/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ส4/หน.", "level_seq_no" => "27.00", "position_type" => "กลุ่มงานสนับสนุน", "position_level" => "ระดับ ส4/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ส7", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช1", "per_type" => "2.00", "level_shortname" => "ช1", "level_seq_no" => "31.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช1", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช1", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช2", "per_type" => "2.00", "level_shortname" => "ช2", "level_seq_no" => "32.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช2", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช2", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช2/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ช2/หน.", "level_seq_no" => "33.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช2/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช3", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช3", "per_type" => "2.00", "level_shortname" => "ช3", "level_seq_no" => "34.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช3", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช4", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช3/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ช3/หน.", "level_seq_no" => "35.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช3/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช5", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช4", "per_type" => "2.00", "level_shortname" => "ช4", "level_seq_no" => "36.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช4", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช6", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ช4/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ช4/หน.", "level_seq_no" => "37.00", "position_type" => "กลุ่มงานช่าง", "position_level" => "ระดับ ช4/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ช7", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ท1", "per_type" => "2.00", "level_shortname" => "ท1", "level_seq_no" => "41.00", "position_type" => "กลุ่มงานเทคนิคพิเศษ", "position_level" => "ระดับ ท1", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ท1", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ท2", "per_type" => "2.00", "level_shortname" => "ท2", "level_seq_no" => "42.00", "position_type" => "กลุ่มงานเทคนิคพิเศษ", "position_level" => "ระดับ ท2", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ท2", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ท2/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ท2/หน.", "level_seq_no" => "43.00", "position_type" => "กลุ่มงานเทคนิคพิเศษ", "position_level" => "ระดับ ท2/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ท3", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ท3", "per_type" => "2.00", "level_shortname" => "ท3", "level_seq_no" => "44.00", "position_type" => "กลุ่มงานเทคนิคพิเศษ", "position_level" => "ระดับ ท3", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ท4", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "0.00", "update_user" => "1.00", "level_name" => "ระดับ ท3/หัวหน้า", "per_type" => "2.00", "level_shortname" => "ท3/หน.", "level_seq_no" => "45.00", "position_type" => "กลุ่มงานเทคนิคพิเศษ", "position_level" => "ระดับ ท3/หัวหน้า", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ท5", "update_date" => "2010-05-31 10:47:01"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "วช", "per_type" => "1.00", "level_shortname" => "วิชาชีพ", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ", "position_level" => "วิชาชีพ", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "สว", "update_date" => "2019-02-07 15:11:42"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว1", "per_type" => "1.00", "level_shortname" => "เจ้าหน้าที่", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 1", "position_level" => "วิชาชีพ 1", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว1", "update_date" => "2018-08-31 09:16:43"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว2", "per_type" => "1.00", "level_shortname" => "เจ้าหน้าที่อาวุโส", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 2", "position_level" => "วิชาชีพ 2", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว2", "update_date" => "2018-08-31 09:16:51"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว3", "per_type" => "1.00", "level_shortname" => "ผู้ช่วยผู้จัดการ", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 3", "position_level" => "วิชาชีพ 3", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว3", "update_date" => "2018-08-31 09:17:01"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว4", "per_type" => "1.00", "level_shortname" => "ผู้จัดการ", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 4", "position_level" => "วิชาชีพ 4", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว4", "update_date" => "2018-08-31 09:17:11"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว5", "per_type" => "1.00", "level_shortname" => "ผู้จัดการอาวุโส", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 5", "position_level" => "วิชาชีพ 5", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว5", "update_date" => "2018-08-31 09:17:21"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "ว6", "per_type" => "1.00", "level_shortname" => "ผู้บริหารสายงาน", "level_seq_no" => "0.00", "position_type" => "วิชาชีพ 6", "position_level" => "วิชาชีพ 6", "level_othername" => NULL, "level_engname" => NULL, "level_no" => "ว6", "update_date" => "2018-08-31 09:17:31"],
            ["level_active" => "1.00", "update_user" => "6830.00", "level_name" => "กลุ่มทั่วไป 1", "per_type" => "1.00", "level_shortname" => "กลุ่มทั่วไป 1", "level_seq_no" => "4.00", "position_type" => "1", "position_level" => "1", "level_othername" => "กลุ่มทั่วไป 1", "level_engname" => NULL, "level_no" => "T1", "update_date" => "2020-01-30 09:29:01"],
            ["level_active" => "1.00", "update_user" => "6830.00", "level_name" => "กลุ่มทั่วไป 2", "per_type" => "1.00", "level_shortname" => "กลุ่มทั่วไป 2", "level_seq_no" => "5.00", "position_type" => "2", "position_level" => "2", "level_othername" => "กลุ่มทั่วไป 2", "level_engname" => NULL, "level_no" => "T2", "update_date" => "2020-01-30 09:24:57"],
            ["level_active" => "1.00", "update_user" => "6830.00", "level_name" => "กลุ่มทั่วไป 3", "per_type" => "1.00", "level_shortname" => "กลุ่มทั่วไป 3", "level_seq_no" => "6.00", "position_type" => "3", "position_level" => "3", "level_othername" => "กลุ่มทั่วไป 3", "level_engname" => NULL, "level_no" => "T3", "update_date" => "2020-01-30 09:27:07"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "กลุ่มวิชาชีพเฉพาะ 3", "per_type" => "1.00", "level_shortname" => "กลุ่มวิชาชีพเฉพาะ 3", "level_seq_no" => "9.00", "position_type" => "3", "position_level" => "3", "level_othername" => "กลุ่มวิชาชีพเฉพาะ 3", "level_engname" => NULL, "level_no" => "V3", "update_date" => "2020-02-22 14:32:50"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพเฉพาะ 4", "per_type" => "1.00", "level_shortname" => "กลุ่มวิชาชีพเฉพาะ 4", "level_seq_no" => "10.00", "position_type" => "4 ", "position_level" => "4", "level_othername" => "กลุ่มวิชาชีพเฉพาะ 4", "level_engname" => NULL, "level_no" => "V4", "update_date" => "2020-01-23 18:02:48"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 2", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 2", "level_seq_no" => "12.00", "position_type" => "2", "position_level" => "2", "level_othername" => "กลุ่มวิชาชีพการลงทุน 2", "level_engname" => NULL, "level_no" => "S6", "update_date" => "2020-01-23 18:03:07"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 3", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 3", "level_seq_no" => "13.00", "position_type" => "3", "position_level" => "3", "level_othername" => "กลุ่มวิชาชีพการลงทุน 3", "level_engname" => NULL, "level_no" => "S7", "update_date" => "2020-01-23 18:03:14"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "กลุ่มวิชาการ 3", "per_type" => "1.00", "level_shortname" => "กลุ่มวิชาการ 3", "level_seq_no" => "7.00", "position_type" => "3", "position_level" => "3", "level_othername" => "กลุ่มวิชาการ 3", "level_engname" => NULL, "level_no" => "s3", "update_date" => "2020-01-21 14:22:56"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาการ 4", "per_type" => "1.00", "level_shortname" => "กลุ่มวิชาการ 4", "level_seq_no" => "8.00", "position_type" => "4", "position_level" => "4", "level_othername" => "กลุ่มวิชาการ 4", "level_engname" => NULL, "level_no" => "s4", "update_date" => "2020-01-23 18:02:34"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 1", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 1", "level_seq_no" => "11.00", "position_type" => "1", "position_level" => "1", "level_othername" => "กลุ่มวิชาชีพการลงทุน 1", "level_engname" => NULL, "level_no" => "S5", "update_date" => "2020-01-23 18:02:59"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มสนับสนุน 1", "per_type" => "1.00", "level_shortname" => "กลุ่มสนับสนุน 1", "level_seq_no" => "1.00", "position_type" => "1", "position_level" => "1", "level_othername" => "กลุ่มสนับสนุน 1", "level_engname" => NULL, "level_no" => "ต1", "update_date" => "2020-01-23 18:01:31"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "กลุ่มสนับสนุน 2", "per_type" => "1.00", "level_shortname" => "กลุ่มสนับสนุน 2", "level_seq_no" => "2.00", "position_type" => "2", "position_level" => "2", "level_othername" => "กลุ่มสนับสนุน 2", "level_engname" => NULL, "level_no" => "ต2", "update_date" => "2020-05-23 10:40:29"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มสนับสนุน 3", "per_type" => "1.00", "level_shortname" => "กลุ่มสนับสนุน 3", "level_seq_no" => "3.00", "position_type" => "3", "position_level" => "3", "level_othername" => "กลุ่มสนับสนุน 3", "level_engname" => NULL, "level_no" => "ต3", "update_date" => "2020-01-23 18:01:50"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 4", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 4", "level_seq_no" => "14.00", "position_type" => "4", "position_level" => "4", "level_othername" => "กลุ่มวิชาชีพการลงทุน 4", "level_engname" => NULL, "level_no" => "S8", "update_date" => "2020-01-23 18:03:22"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 5", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 5", "level_seq_no" => "15.00", "position_type" => "5", "position_level" => "5", "level_othername" => "กลุ่มวิชาชีพการลงทุน 5", "level_engname" => NULL, "level_no" => "S9", "update_date" => "2020-03-12 14:59:40"],
            ["level_active" => "1.00", "update_user" => "12372.00", "level_name" => "กลุ่มวิชาชีพการลงทุน 6", "per_type" => "1.00", "level_shortname" => "วิชาชีพการลงทุน 6", "level_seq_no" => "16.00", "position_type" => "6", "position_level" => "6", "level_othername" => "กลุ่มวิชาชีพการลงทุน 6", "level_engname" => NULL, "level_no" => "S0", "update_date" => "2020-01-23 18:03:37"],
            ["level_active" => "1.00", "update_user" => "1.00", "level_name" => "กลุ่มเชี่ยวชาญ ", "per_type" => "1.00", "level_shortname" => "กลุ่มเชี่ยวชาญ ", "level_seq_no" => "0.00", "position_type" => NULL, "position_level" => NULL, "level_othername" => "กลุ่มเชี่ยวชาญ ", "level_engname" => NULL, "level_no" => "V6", "update_date" => "2020-01-27 17:58:22"],


        ]);
    }
}
