INSERT INTO DPISEMP1.PER_IPIP (IPIP_ID,KF_ID,DEVELOP_SEQ,DEVELOP_COMPETENCE,DEVELOP_METHOD,DEVELOP_INTERVAL,UPDATE_USER,UPDATE_DATE,DEVELOP_EVALUATE) VALUES
	 (1,4,1,'เมื่อสำนักงาน กพ.มีการเปลี่ยนแปลงฐานข้อมูลให้พัฒนางานตามที่สำนักงาน กพ.พัฒนาด้วย',NULL,NULL,1,'2021-09-03 14:33:40',NULL);
